Pizzas/pizzas_log/urls.py
"""Define padrões de URL para pizzas_log"""

from django.urls import path

from . import views

app_name = 'pizzas_log'
urlpatterns = [
    # Página inicial
    path('', views.index, name='index'),
    # Página que mostra todos os ingredientes
    path('pizzas/', views.pizzas, name='pizzas'),
    # Página de detalhes para um único tópico
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

Pizzas/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas_log.urls'))
]

Pizzas/pizzas_log/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

Pizzas/pizzas_log/views.py
from django.shortcuts import render
from .models import Pizza
# Create your views here.


def index(request):
    """A página inicial para o Registro de Aprendizagem"""
    return render(request, 'pizzas_log/index.html')


def pizzas(request):
    """Mostra todas as pizzas"""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas_log/pizzas.html', context)


def pizza(request, pizza_id):
    """Mostra um único tópico"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas_log/pizza.html', context)

Pizzas/pizzas_log/templates/pizzas_log/base.html
<p>
    <a href="{% url 'pizzas_log:index' %}">Pizzas</a> - 
    <a href="{% url 'pizzas_log:pizzas' %}">Sabores</a> 

</p>

{% block content %}{% endblock content %}

Pizzas/pizzas_log/templates/pizzas_log/index.html
{% extends 'pizzas_log/base.html' %}

{% block content %}

<p>Aqui você verá as pizzas disponíveis e seus ingredientes!</p>
{% endblock content %}

Pizzas/pizzas_log/templates/pizzas_log/pizza.html
{% extends 'pizzas_log/base.html' %}

{% block content %}

<p>Pizzas: {{ pizza.name }}</p>

<p>Ingredientes:</p>

<ul>
    {% for topping in toppings %}
      <li>
        <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ topping.text|linebreaks }}</p>
      </li>
    {% empty %}
      <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

Pizzas/pizzas_log/templates/pizzas_log/pizzas.html
{% extends 'pizzas_log/base.html' %}

{% block content %}
<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas_log:pizza' pizza.id %}">
          {{ pizza.name }}</a>
      </li>
    {% empty %}
      <li>Nenhuma pizza foi adicionada.</li>
    {% endfor %}
</ul>

{% endblock content %}